"""
modules/cart/models.py — Taomly Platform
Phase 6: Cart Engine ORM models.

Tables:
  carts              — one active cart per (session_id, restaurant_id)
  cart_items         — items with server-authoritative unit_price snapshot
  cart_item_modifiers — modifier option snapshots per cart item

Architecture decisions:
  - location_id NOT stored in carts (request context via X-Location-Id)
  - currency snapshot from Location.currency at cart creation time
  - session_id is an opaque UUID4 bearer token generated by the client
  - telegram_id nullable — auxiliary lookup only, not cart identity
  - CartItem identity enforced by functional unique index in migration:
      UNIQUE (cart_id, product_id, COALESCE(variant_id, 0), modifiers_hash)
  - modifiers_hash = full SHA-256 hex (64 chars) of sorted validated option IDs
  - unit_price is a snapshot from first creation — not updated on subsequent adds
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    TIMESTAMP,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from database import Base


# ──────────────────────────────────────────
# CART
# ──────────────────────────────────────────
class Cart(Base):
    """
    Server-side shopping cart.

    Identity: (session_id, restaurant_id) — enforced by unique index.
    session_id: opaque UUID4, generated by client, stored in localStorage/CloudStorage.
    telegram_id: NULL for browser/PWA guests; set to tg_user.id for Telegram users.
                 Auxiliary only — not used for cart ownership in Phase 6.
    currency: snapshot from Location.currency at cart creation.
              Mutations rejected with 409 if X-Location-Id currency differs.
    status: 'active' | 'checked_out' | 'abandoned'
            Phase 6 only uses 'active'. Phase 7 sets 'checked_out'.
    """
    __tablename__ = "carts"
    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'checked_out', 'abandoned')",
            name="ck_carts_status",
        ),
        CheckConstraint(
            "currency IN ('UZS', 'KZT', 'RUB', 'USD', 'TRY', 'AED')",
            name="ck_carts_currency",
        ),
        Index("ix_carts_session_restaurant", "session_id", "restaurant_id", unique=True),
        Index(
            "ix_carts_telegram_restaurant",
            "telegram_id",
            "restaurant_id",
            postgresql_where="telegram_id IS NOT NULL",
        ),
    )

    id            = Column(BigInteger, primary_key=True)
    restaurant_id = Column(
        BigInteger,
        ForeignKey("restaurants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id    = Column(String(64), nullable=False)
    telegram_id   = Column(BigInteger, nullable=True)
    currency      = Column(String(10), nullable=False)
    status        = Column(String(20), nullable=False, default="active", server_default="active")
    created_at    = Column(TIMESTAMP(timezone=True), server_default=func.now(), nullable=False)
    updated_at    = Column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    restaurant = relationship("Restaurant", lazy="select")
    items      = relationship(
        "CartItem",
        back_populates="cart",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="CartItem.id",
    )

    def __repr__(self) -> str:
        return (
            f"<Cart id={self.id} restaurant_id={self.restaurant_id} "
            f"session={self.session_id!r} status={self.status!r}>"
        )


# ──────────────────────────────────────────
# CART ITEM
# ──────────────────────────────────────────
class CartItem(Base):
    """
    One line in a Cart.

    unit_price: server-authoritative snapshot from Product/Variant at add time.
                NEVER updated on subsequent identical adds — quantity increments instead.
    modifiers_hash: full SHA-256 hex (64 chars) of sorted validated modifier_option IDs.
                    Empty string ("") for items with no modifiers is intentionally avoided;
                    sha256("") hex constant is used instead for DB uniqueness safety.
    line_total: unit_price × quantity, always computed server-side.

    Uniqueness: functional unique index in migration enforces one CartItem per
    (cart_id, product_id, COALESCE(variant_id, 0), modifiers_hash).
    Concurrent identical adds use INSERT ... ON CONFLICT DO UPDATE (atomic).
    """
    __tablename__ = "cart_items"
    __table_args__ = (
        CheckConstraint("quantity > 0", name="ck_cart_items_quantity_positive"),
        CheckConstraint("unit_price >= 0", name="ck_cart_items_unit_price_nonneg"),
        CheckConstraint("line_total >= 0", name="ck_cart_items_line_total_nonneg"),
        Index("ix_cart_items_cart_id", "cart_id"),
    )

    id             = Column(BigInteger, primary_key=True)
    cart_id        = Column(
        BigInteger,
        ForeignKey("carts.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # covered by ix_cart_items_cart_id
    )
    product_id     = Column(
        BigInteger,
        ForeignKey("products.id", ondelete="CASCADE"),
        nullable=False,
    )
    variant_id     = Column(
        BigInteger,
        ForeignKey("product_variants.id", ondelete="CASCADE"),
        nullable=True,
    )
    quantity       = Column(Integer, nullable=False)
    unit_price     = Column(Integer, nullable=False)   # snapshot: never overwritten
    modifiers_hash = Column(String(64), nullable=False) # SHA-256 full hex or sha256("") hex
    notes          = Column(Text, nullable=True)
    line_total     = Column(Integer, nullable=False)   # unit_price × quantity, server-computed
    added_at       = Column(TIMESTAMP(timezone=True), server_default=func.now(), nullable=False)
    updated_at     = Column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    cart    = relationship("Cart", back_populates="items", lazy="select")
    product = relationship("Product", lazy="select")
    variant = relationship("ProductVariant", lazy="select")
    modifiers = relationship(
        "CartItemModifier",
        back_populates="cart_item",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="CartItemModifier.id",
    )

    def __repr__(self) -> str:
        return (
            f"<CartItem id={self.id} cart_id={self.cart_id} "
            f"product_id={self.product_id} qty={self.quantity} "
            f"unit_price={self.unit_price}>"
        )


# ──────────────────────────────────────────
# CART ITEM MODIFIER
# ──────────────────────────────────────────
class CartItemModifier(Base):
    """
    Snapshot of a selected ModifierOption in a CartItem.

    name and price_adjustment are snapshots from DB at add time.
    Client-supplied values are never accepted (ADR-S2-8-2 pattern).

    On Phase 7 Cart → Order conversion, these snapshots transfer directly
    to OrderItemModifier without re-reading the menu.

    FK behavior:
      cart_item_id:      CASCADE DELETE
      modifier_option_id: SET NULL (snapshot preserved if option deleted)
    """
    __tablename__ = "cart_item_modifiers"
    __table_args__ = (
        Index("ix_cart_item_modifiers_item_id", "cart_item_id"),
    )

    id                 = Column(BigInteger, primary_key=True)
    cart_item_id       = Column(
        BigInteger,
        ForeignKey("cart_items.id", ondelete="CASCADE"),
        nullable=False,
        index=False,  # covered by ix_cart_item_modifiers_item_id
    )
    modifier_option_id = Column(
        BigInteger,
        ForeignKey("modifier_options.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Snapshot fields — sourced exclusively from DB, never from client.
    name             = Column(String(255), nullable=False)
    price_adjustment = Column(Integer, nullable=False)

    cart_item = relationship("CartItem", back_populates="modifiers", lazy="select")

    def __repr__(self) -> str:
        return (
            f"<CartItemModifier id={self.id} cart_item_id={self.cart_item_id} "
            f"name={self.name!r} adj={self.price_adjustment}>"
        )
